spring.application.name=purchase-service
server.port=8083

# =========================================================
# Oracle Database
# =========================================================

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freepdb1
spring.datasource.username=creditcard_user
spring.datasource.password=MyPassword123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# =========================================================
# JPA
# =========================================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# REST client
# =========================================================

card.service.url=http://localhost:8082