spring.application.name=credit-card-service
server.port=8082

# Set these environment variables to match your Oracle SQL Developer connection.

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/freepdb1
spring.datasource.username=creditcard_user
spring.datasource.password=MyPassword123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# Use the CREDIT_CARD table created in Oracle; do not silently modify its schema.
#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true